### ISSUE TITLE
Making your code Python 3 compatible

### ISSUE THREAD

**Issue by dhruvv** [gautamdayal/My-Code#1]
Python 2 will be obsoleted soon. Only 1 change has to be made to make your code Py3 compatible.

**Comment by gautamdayal** [comment]
Ok I'll do that. I'll make two versions; one for 2 and one for 3. A lot of people still use 2 so...

**Comment by gautamdayal** [comment]
Wait but the Tkinter library code is different for Py3 right. I'll have to change all of that.

**Comment by gautamdayal** [comment]
Never mind all I have to do is change `Tkinter` to `tkinter`
